<x-app-layout>
<x-slot name="header"><div class="flex items-end justify-between"><div><h1 class="text-2xl font-bold text-slate-900">Leads</h1><p class="mt-1 text-sm text-slate-500">Server-side filtering built for large datasets.</p></div><a href="{{ route('leads.create') }}" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">Add lead</a></div></x-slot>
<div class="p-5 lg:p-8">
<form class="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-4 xl:grid-cols-6">
@foreach(['category','country','state','city','phone_type','source'] as $f)<select name="{{ $f }}" class="rounded-lg border-slate-200 text-sm"><option value="">{{ str($f)->replace('_',' ')->title() }}</option>@foreach($options[$f] as $v)<option @selected(request($f)===$v)>{{ $v }}</option>@endforeach</select>@endforeach
<select name="email_status" class="rounded-lg border-slate-200 text-sm"><option value="">Email status</option>@foreach(['unknown','valid','invalid','catch_all','bounced'] as $v)<option value="{{ $v }}" @selected(request('email_status')===$v)>{{ str($v)->replace('_',' ')->title() }}</option>@endforeach</select><select name="lead_status" class="rounded-lg border-slate-200 text-sm"><option value="">Lead status</option>@foreach(['new','queued','contacted','opened','clicked','replied','interested','not_interested','unsubscribed','closed'] as $v)<option value="{{ $v }}" @selected(request('lead_status')===$v)>{{ str($v)->replace('_',' ')->title() }}</option>@endforeach</select><select name="email_availability" class="rounded-lg border-slate-200 text-sm"><option value="">Any email</option><option value="yes" @selected(request('email_availability')==='yes')>Has email</option><option value="no" @selected(request('email_availability')==='no')>No email</option></select><select name="website_availability" class="rounded-lg border-slate-200 text-sm"><option value="">Any website</option><option value="yes" @selected(request('website_availability')==='yes')>Has website</option><option value="no" @selected(request('website_availability')==='no')>No website</option></select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Filter</button><a href="{{ route('leads.index') }}" class="py-2 text-center text-sm font-semibold text-slate-500">Clear</a>
</form>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-4 py-4">Name</th><th class="px-4 py-4">Business Name</th><th class="px-4 py-4">Email</th><th class="px-4 py-4">Phone</th><th class="px-4 py-4">Website</th><th class="px-4 py-4">Score</th><th class="px-4 py-4">Last Call</th><th class="px-4 py-4">Call Note</th><th class="px-4 py-4">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($leads as $lead)<tr class="hover:bg-slate-50"><td class="px-4 py-4 font-semibold text-slate-900">{{ $lead->contact_person ?: trim($lead->first_name.' '.$lead->last_name) ?: '—' }}</td><td class="px-4 py-4"><div class="font-semibold text-slate-900">{{ $lead->business_name ?: '—' }}</div><div class="text-xs text-slate-500">{{ $lead->category }}</div></td><td class="px-4 py-4">@if($lead->email)<a href="mailto:{{ $lead->email }}" class="text-indigo-600 hover:underline">{{ $lead->email }}</a>@else<span class="text-slate-400">No email</span>@endif</td><td class="whitespace-nowrap px-4 py-4">{{ $lead->phone ?: 'No phone' }}</td><td class="max-w-56 px-4 py-4">@if($lead->website)@php($websiteUrl = str_starts_with($lead->website, 'http://') || str_starts_with($lead->website, 'https://') ? $lead->website : 'https://'.$lead->website)<a href="{{ $websiteUrl }}" target="_blank" rel="noopener noreferrer" class="block truncate text-indigo-600 hover:underline">{{ $lead->website }}</a>@else<span class="text-slate-400">No website</span>@endif</td><td class="px-4 py-4"><span class="rounded-lg bg-slate-100 px-2.5 py-1 font-black">{{ $lead->lead_score }}</span></td><td class="whitespace-nowrap px-4 py-4 text-xs">{{ $lead->latestCall?->started_at?->format('M j, Y') ?: '—' }}<br><span class="text-slate-400">{{ $lead->latestCall?->started_at?->format('g:i A') }}</span></td><td class="max-w-56 px-4 py-4"><span class="block truncate" title="{{ $lead->latestCall?->notes }}">{{ $lead->latestCall?->notes ?: '—' }}</span></td><td class="whitespace-nowrap px-4 py-4"><div class="flex gap-3">@if($lead->phone)<button type="button" class="call-now rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white" data-url="{{ route('leads.call',$lead) }}" data-name="{{ $lead->business_name ?: $lead->phone }}">☎ Call Now</button>@endif<a href="{{ route('leads.edit',$lead) }}" class="self-center font-bold text-indigo-600">Edit</a></div></td></tr>
@empty<tr><td colspan="9" class="px-5 py-16 text-center text-slate-500">No leads match these filters.</td></tr>@endforelse
</tbody></table></div><div class="border-t border-slate-200 p-4">{{ $leads->links() }}</div></div>
</div>

<div id="call-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/70 p-4"><div class="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div class="text-xs font-black uppercase tracking-wider text-indigo-600">Call completed</div><h2 id="call-lead-name" class="mt-1 text-2xl font-black"></h2><p id="call-time" class="mt-1 text-sm text-slate-500"></p><form id="call-summary-form" class="mt-6 space-y-4"><label class="block text-sm font-bold">Outcome<select name="disposition" class="mt-1 w-full rounded-xl border-slate-200">@foreach(['answered','no_answer','busy','callback','interested','wrong_number','not_interested'] as $value)<option value="{{ $value }}">{{ str($value)->replace('_',' ')->title() }}</option>@endforeach</select></label><label class="block text-sm font-bold">Caller summary / notes<textarea name="notes" required rows="4" placeholder="What happened on this call?" class="mt-1 w-full rounded-xl border-slate-200"></textarea></label><label class="flex items-center gap-2 rounded-xl border p-3 text-sm font-bold"><input id="follow-up-check" type="checkbox" name="follow_up" value="1" class="rounded border-slate-300"> Follow Up</label><label id="follow-up-date-wrap" class="hidden text-sm font-bold">Follow-up date and time<input id="follow-up-at" type="datetime-local" name="follow_up_at" class="mt-1 w-full rounded-xl border-slate-200"></label><p id="call-form-error" class="hidden rounded-lg bg-rose-50 p-3 text-sm text-rose-700"></p><button class="w-full rounded-xl bg-slate-950 py-3 font-black text-white">Save Call Summary</button></form></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const csrf=document.querySelector('meta[name="csrf-token"]').content,modal=document.getElementById('call-modal'),form=document.getElementById('call-summary-form'),error=document.getElementById('call-form-error');let callId=null,poller=null,leadName='';document.getElementById('follow-up-check').addEventListener('change',e=>{document.getElementById('follow-up-date-wrap').classList.toggle('hidden',!e.target.checked);document.getElementById('follow-up-at').required=e.target.checked;});document.querySelectorAll('.call-now').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;button.textContent='Opening Zoom…';try{const response=await fetch(button.dataset.url,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,Accept:'application/json'}}),data=await response.json();if(!response.ok)throw new Error(data.message||'Call could not start.');callId=data.call_id;leadName=button.dataset.name;window.location.href=data.dial_url;poller=setInterval(checkState,2000);}catch(e){alert(e.message);button.disabled=false;button.textContent='☎ Call Now';}}));async function checkState(){const response=await fetch(`{{ url('/calls') }}/${callId}/state`,{headers:{Accept:'application/json'}}),data=await response.json();if(data.status==='completed'){clearInterval(poller);document.getElementById('call-lead-name').textContent=leadName;document.getElementById('call-time').textContent=`Called ${new Date(data.started_at).toLocaleString()}`;form.action=`{{ url('/calls') }}/${callId}/complete`;modal.classList.remove('hidden');modal.classList.add('flex');}}form.addEventListener('submit',async e=>{e.preventDefault();error.classList.add('hidden');const response=await fetch(form.action,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,Accept:'application/json'},body:new FormData(form)}),data=await response.json();if(!response.ok){error.textContent=data.message||Object.values(data.errors||{}).flat().join(' ');error.classList.remove('hidden');return;}window.location.href=data.redirect;});});
</script>
</x-app-layout>
